### ISSUE TITLE
Manix

### ISSUE THREAD

**Issue by IogaMaster** [nix-community/infra#1078]
The original manix is unmaintained:
https://github.com/mlvzk/manix

I have sent @lecoqjacob, an email in which he agrees to add it (we will continue to talk on discord about details).
Here is his fork of manix, which has improved upon the original manix source: https://github.com/lecoqjacob/manix

I would like to maintain it here in the nix-community organization.

**Comment by lecoqjacob** [comment]
I spoke briefly with @IogaMaster about moving manix to fall under mix community and thus be maintained. I approve of this request and I am available for any transition needed. If I am still able to provide maintenance for manix, that would be appreciated, but up to nix-community

**Comment by Mic92** [comment]
@lecoqjacob I sent you an invite you can accept by visiting: https://github.com/nix-community/

**Comment by IogaMaster** [comment]
@lecoqjacob I would love to help maintain manix. Would you like me to make pr's or add me to the team where I can commit directly.

I will attempt to get into contact with the original creator of manix and see if we can have his page redirect to the new nix-community project version.

**Comment by lecoqjacob** [comment]
@IogaMaster @Mic92 The repo has been transferred this morning and should now reside under `nix-community`.

@IogaMaster I would love to add you as a maintainer. Once the repo has been setup, I will add you :)

**Comment by IogaMaster** [comment]
I see it, how can we make issues come back?

**Comment by IogaMaster** [comment]
@lecoqjacob here is how to do both:

Adding me:
https://github.com/nix-community/manix/settings/access
Then add me to the team that is there.

Issues on a fork:
https://github.com/nix-community/manix/settings
This check this box.
![image](https://github.com/nix-community/infra/assets/67164465/3bf950ec-407a-4028-8f28-da1d1b603094)

**Comment by IogaMaster** [comment]
@Mic92 lecoqjacob dm'ed me on Discord.
He does not have access to the manix repo now that it has been transferred.
Could you make him admin and add a team?

**Comment by IogaMaster** [comment]
Everything is now done, thanks Mic!
