### ISSUE TITLE
Require build-box users to be in a shared space

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#1147]
* the boxes are shared resources
* users might bump into each other in terms of CPU or disk consumption
* this likelihood is increasing with the number of users

We should set up a shared space where they can talk, like a Matrix channel, and enforce it. This could also be a good entry point for users to request access to the builders.

What do you think?

**Comment by zowoq** [comment]
Good idea.

Are you proposing a separate matrix channel or using #nix-community:nixos.org?

Matrix channel may also be a better alternative to https://github.com/nix-community/infra/issues/604, trying to get all of our members/collaborators into a github team.

**Comment by zimbatm** [comment]
Ok, yeah, we could add #nix-community-builders:nixos.org, for example. This would be a subset of #604 right?

**Comment by zowoq** [comment]
Existing #nix-community channel isn't really high traffic, I guess we could use that, might be simpler? Don't feel strongly either way.

> This would be a subset of https://github.com/nix-community/infra/issues/604 right?

Similar idea of having a communication channel but for different groups, that issue I was only really thinking of the github side of the org, repo maintainers, etc.

**Comment by Mic92** [comment]
I also think #nix-community is enough. I already have too many channels to read. If it becomes too busy there, we can relocate this.
