### ISSUE TITLE
build02 (nixpkgs-update bot) is down

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#1362]
Stuck at boot, zfs import error, tried reinstalling, same error.

I think it is a hardware issue but not sure what the problem is yet.

Not sure how much time I'll have to work on this today.

**Comment by Mic92** [comment]
Any S.M.A.R.T. values?

**Comment by zowoq** [comment]
I left the hwcheck tool running for a while and it doesn't seem to have done anything.

It is in rescue mode and you key is loaded if you want to have a look at it.

**Comment by Mic92** [comment]
Thanks. I am currently in parallel fixing another server. I have a look

**Comment by Mic92** [comment]
Zfs support in the rescue system is broken so I did this:

curl -L https://github.com/nix-community/nixos-images/releases/download/nixos-unstable/nixos-kexec-installer-noninteractive-x86_64-linux.tar.gz | tar -xzf- -C /root
/root/kexec/run

**Comment by Mic92** [comment]
Both nvme's look ok according to smartmontools:

```
Available Spare:                    100%
Available Spare Threshold:          10%
```

**Comment by Mic92** [comment]
Zfs scrub is happy so far.

**Comment by Mic92** [comment]
I also run out of time just now. If the problem still persist in the evening, I am going to have a look with the kvm console.

**Comment by Mic92** [comment]
Ok. I will order one now.

**Comment by Mic92** [comment]
All it needed was a `zpool import -f zroot`...
I think I will make the default in disko. The amount of installations that gets messed up by this is higher than the few iscsi users that might import a block devices not meant for them.

**Comment by Mic92** [comment]
Ok. Weird: https://github.com/NixOS/nixpkgs/blob/249fbde2a178a2ea2638b65b9ecebd531b338cf9/nixos/modules/tasks/filesystems/zfs.nix#L650C28-L650C43
This should be already true.

**Comment by Mic92** [comment]
Ok. looks like the same issue happens again after reboot. Maybe the timeout for the device is too short.

**Comment by Mic92** [comment]
Now it imports the pool instant again.

**Comment by zowoq** [comment]
Thanks for fixing this. I'll restore the nixpkgs-update logs from the backup.

**Comment by Mic92** [comment]
Ok. I didn't had to reformat anything, but you probably did before.
