### ISSUE TITLE
Using screen or tmux

### ISSUE THREAD

**Issue by Nebucatnetzer** [nix-community/infra#165]
I was just thinking a bit about the deploy script a bit.
Would it be possible to extend it, so that it uses screen or tmux when executing the tasks on the remote machine.

The idea is to make it less problematic in case the connection breaks or `nixos-rebuild` takes a long time and you can disconnect and reconnect at a later point.

**Comment by Mic92** [comment]
One could use `systemd-run` to create a transient systemd service to run nixos-rebuild in a service.
