### ISSUE TITLE
niv-updater-action without PR description

### ISSUE THREAD

**Issue by knl** [nix-community/infra#171]
Dear nix-community team,

I've noticed that you're running niv-updater-action without PR descriptions (the changelog). As I'm constantly looking to improve my software and help people, I'm wondering why you're doing it that way? Would you prefer to have something else in the PR description? 

I've created an issue for your usecase: https://github.com/knl/niv-updater-action/issues/51

Thanks,
Nikola

**Comment by zimbatm** [comment]
Hey Nikola,

It's probably just a taste thing. /cc @Mic92 to give you more context.

Thanks for building the action, it's nice.

**Comment by Mic92** [comment]
We used to log all PRs to our nix-community matrix channel and niv updater bumps were quite long and a bit spammy, which is why I removed the description. Now that we moved those messages to a dedicated monitoring channel we could potentially re-introduce them.

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/infra/commit/d0de771debd8bf5d5a65e83ad838876cd4694996

**Comment by knl** [comment]
Thanks for your kind words @zimbatm :)

Thanks for clarifying what was behind your change, and this issue didn't require any change. I was really just wondering what is the motivation to remove descriptions. I'll finish that change this week, so you can turn it off easily in case the need arises. 

And final thanks for keeping the nix infra running :)
