### ISSUE TITLE
Auto-upload built binaries to Cachix

### ISSUE THREAD

**Issue by adisbladis** [nix-community/infra#2]
Using the new post build hook https://github.com/NixOS/nix/pull/2995

**Comment by zimbatm** [comment]
good idea!

**Comment by adisbladis** [comment]
w00t! This one can be closed now!
https://github.com/nix-community/infra/commit/85e1d29b94aa2bf9662d7c33ad9d2d7d3f119c3b

**Comment by zimbatm** [comment]
<3 progress!
