### ISSUE TITLE
aarch64 builds on Hydra seem to fail

### ISSUE THREAD

**Issue by vikanezrimaya** [nix-community/infra#220]
It looks like there is a machine that could be used for building `aarch64-linux` packages, `build04` - however, it doesn't seem to be used and builds are instead rejected with "Unsupported system type". Is this intentional?

Example failing build: https://hydra.nix-community.org/build/14455702

**Comment by Mic92** [comment]
It's not set up as a remote builder yet.

**Comment by zowoq** [comment]
@Mic92 Can we add `build04` as an remote builder on `build01` as well?

**Comment by Mic92** [comment]
Done.

**Comment by zowoq** [comment]
Thanks!

**Comment by vikanezrimaya** [comment]
https://hydra.nix-community.org/eval/592355#tabs-unfinished &mdash; stuck in queue for an hour, according to [queue summary](https://hydra.nix-community.org/queue-summary). Is this expected?

**Comment by Mic92** [comment]
This issue has been fixed as well.
