### ISSUE TITLE
Deployment permissions for timokau

### ISSUE THREAD

**Issue by timokau** [nix-community/infra#31]
Since nix-community now hosts marvin-mk2, it would be nice if I could deploy new versions myself. This is especially relevant on major changes where I'd like to control the timing and fixes which should be deployed quickly.

In addition to that, I'd like to transfer the bot instance itself (https://github.com/apps/marvin-mk2) to nix-community to reduce dependency on a single person, but to do that I while maintaining access to the admin interface I think I would need to be a member.

Previously discussed in https://github.com/nix-community/infra/issues/24 and privately with @adisbladis.

CC @adisbladis @flokli @grahamc @nlewo @ryantm @zimbatm

**Comment by ryantm** [comment]
I am fine with timokau being added to the list of people who can access the secrets. I'd appreciate it if everyone with access post their approval of (or an objection to) the addition.

**Comment by zimbatm** [comment]
@ryantm holds the most sensitive secrets so if you are fine I am fine too.

@timokau how about we organize a quick video chat to say hello to each-other?

**Comment by adisbladis** [comment]
I'm good with @timokau getting deployment permissions.

**Comment by nlewo** [comment]
I'm also good with @timokau getting deployment permissions.

Having a quick video call is a good idea!

**Comment by zimbatm** [comment]
sent the invite to @nix-community/infra in the meantime, assuming that it's all good.

**Comment by timokau** [comment]
> how about we organize a quick video chat to say hello to each-other?

Sounds good. If its just a quick informal chat I could do this evening (CEST), i.e. something in between 6-9 hours from now. If we actually want to have everyone there it would probably need more scheduling effort.

> sent the invite to @nix-community/infra in the meantime, assuming that it's all good.

Great, received & accepted!

**Comment by zimbatm** [comment]
Since it's short notice I propose 20h00 GMT+2. Everyone in the team is welcome to join:

https://calendar.google.com/event?action=TEMPLATE&tmeid=MWVtMWh2NHUzOGQ1bWRscWw3M2FrbzRybjggemltYmF0bUB6aW1iYXRtLmNvbQ&tmsrc=zimbatm%40zimbatm.com

**Comment by timokau** [comment]
I'll be there :) How/where do we meet? We could do https://meet.jit.si/nix-community.

**Comment by zimbatm** [comment]
I am having reliability issues with meet.jit.si at the moment. https://meet.google.com/rmt-hpgm-sav?hs=122&authuser=0 is included with the calendar invite but open to using anything that works.

**Comment by timokau** [comment]
Ah, the calendar invite didn't work for some reason and I don't really use google calendar anyways so I didn't look into it further.

We could try jitsi and fall back on google meet if there are technical difficulties. I'd prefer something you don't need an account for, though google would be okay if jitsi doesn't work.

I think jitsi still has some issues on firefox, maybe that was it.

**Comment by ryantm** [comment]
@timokau and I are in the jitsi room. I'm having trouble getting into the Google one.

**Comment by timokau** [comment]
Thanks for tanking the time :)
