### ISSUE TITLE
Rules for administrators

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#321]
@adisbladis
@flokli
@grahamc
@Mic92
@nlewo
@ryantm
@zimbatm
@zowoq

I propose to write down a few rules for the administrators of this project for transparency reasons and to make it more democratic.

### Responsibilities as an administrator

Our mission is to support the users of the org, and the Nix project in general.

This is a voluntary effort, on a best-effort basis. Things that are good to do are:
* keep the systems updated and patched
* reply to user requests
* host new services that could help the project

### Quorum of 5

To reduce the attack surface on the project, I propose limiting the number of administrators to 5 people.

In the current configuration, I propose to keep Mic92 and zowoq because they are actively managing the infra, and ryantm so he can deploy his bot. That leaves 2 other people from the existing list.

### How to become an administrator

In order to become an administrator, we ask that you already started contributing to this repo through PRs, and that you are trustworthy. Trust is built on top of personal relationships and past behaviour.

Right now we trust everybody on this list, so that makes it easy for you to come back.

---
Did I miss anything? Does that sound reasonable?

**Comment by zowoq** [comment]
Need to clarify what "administrator" means, admin access to this repo, sudo on the boxes and access to the sops secrets?

`nix-community` owners have commit access to this repo anyway ...

Who's responsible for dealing with the hetzner and oracle accounts?

**Comment by zimbatm** [comment]
Good question.

I think that the easiest would be to give administrators all the accesses:
* sudo on the boxes
* access to the sops secrets
* access to SaaS/Cloud accounts that we use (using sops shared secrets if we can't issue individual accounts)
* ownership on the org so they can fix teams and repo ownerships, set repo and org-level secrets, ...

Right now, the servers are funded by @ryantm and @numtide, so some access might be limited there. In the long run, I would like to create an umbrella organization to hold those and the domain.

**Comment by Mic92** [comment]
The oracle account was provided by me for aarch64.

**Comment by zowoq** [comment]
> To reduce the attack surface on the project, I propose limiting the number of administrators to 5 people.

> I think that the easiest would be to give administrators all the accesses ... sudo on the boxes .. ownership on the org

Will org ownership be limited to just the five administrators? Owners can give themselves sudo and read some secrets straight off the boxes, etc.

Don't really see a way around this without switching to manual deployments or moving the infra repo out of this org.

**Comment by zimbatm** [comment]
Yes, the ownership should only be given to the admins. We're assuming that everybody is acting in good faith.

Based on usage, I propose the following new list:

@adisbladis
@Mic92
@ryantm
@zimbatm
@zowoq

I'll update the docs and make the changes in a few days.

**Comment by zimbatm** [comment]
Implemented in https://github.com/nix-community/infra/pull/383.
