### ISSUE TITLE
merge `nix-community/aarch64-build-box` into this repo

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#323]
This has been mentioned on `#nix-community` matrix a few times now.

**Comment by zowoq** [comment]
https://github.com/nix-community/aarch64-build-box/blob/69bf35573e2b3b98fe36b13708f7a86c1e8920da/enter-env.sh#L27
```
export PACKET_AUTH_TOKEN=$(vault kv get -field api_key_token packet/creds/nixos-foundation)
```

@zimbatm It looks like it is provisioned under the nixos foundation, if you have access could we just wipe the machine and start over?

**Comment by zimbatm** [comment]
Let me check, I need to ask @grahamc

**Comment by Mic92** [comment]
I think those keys were a bit problematic to share because they are also used for other builders that are used in hydra.nixos.org.
Maybe the whole deployment could be adapted to not require those keys.

**Comment by zowoq** [comment]
I'd like to drop the ephemeral netboot stuff and just treat it as a regular machine like the others in this repo. 

We don't all need to have access to the key if it's only needed for the initial setup, should be fine as long as we always have someone in the community admin group that does have access to it.

**Comment by Mic92** [comment]
Sounds good to me.

**Comment by zowoq** [comment]
Don't suppose packet might be willing to provide nix-community with hardware directly?

**Comment by zowoq** [comment]
As this doesn't seem to be going anywhere the easiest option might be just move https://github.com/nix-community/aarch64-build-box to https://github.com/NixOS and wash our hands of it.

Currently aarch64-build-box is set as a remote builder for build01 so I'd remove the nix-community user on aarch64-build-box first before moving it.

**Comment by zimbatm** [comment]
Agreed. If we could get a bit more funding, we could afford to get https://www.hetzner.com/dedicated-rootserver/rx170

**Comment by zowoq** [comment]
> As this doesn't seem to be going anywhere the easiest option might be just move https://github.com/nix-community/aarch64-build-box to https://github.com/NixOS and wash our hands of it.
> 
> Currently aarch64-build-box is set as a remote builder for build01 so I'd remove the nix-community user on aarch64-build-box first before moving it.

I've opened https://github.com/nix-community/infra/pull/681 and https://github.com/nix-community/aarch64-build-box/pull/161

**Comment by zowoq** [comment]
@zimbatm I've merged those PRs so the repo can be moved to nixos org.

**Comment by zimbatm** [comment]
I'll just archive the repo since the box is now offline.
https://github.com/nix-community/aarch64-build-box/pull/164

This issue can also be closed
