### ISSUE TITLE
on build01, nix-build seems to hang

### ISSUE THREAD

**Issue by ryantm** [nix-community/infra#33]
nixpkgs-update has been stuck for a day trying to do nixpkgs-review for `pythonPackages.fastapi`, a package with only 10 reverse dependencies. It seems like nix-build is not reliably running. I've left it in this state in case someone with more knowledge about the nix-daemon or nix-build can diagnose the problem more.

@zimbatm thinks it might be a problem with the nix-daemon having trouble with man concurrent builds

cc @adisbladis

**Comment by ryantm** [comment]
This is still happening.

**Comment by ryantm** [comment]
A nixpkgs-review spawned by nixpkgs-update got stuck for a few days.

**Comment by Mic92** [comment]
Probaly no longer an issue because we have build02?
