### ISSUE TITLE
Enable discussions on the org?

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#388]
Should we try to enable the discussions? This might help create a more community feel to the org. Let people raise issues, and have longer form communication than on the Matrix channel.

![image](https://user-images.githubusercontent.com/3248/213860793-214d2e2f-e4c2-40b1-bbf2-4fcc3f077aae.png)

**Comment by zowoq** [comment]
Seems like a good idea, less friction to use and doesn't fragment or obscure discussion like running another separate forum would.

👍

**Comment by zimbatm** [comment]
Ok, we can try it and see how it goes

**Comment by zimbatm** [comment]
I'm also proposing that we announce infrastructure changes in the forum, as per:
https://github.com/orgs/nix-community/discussions/401
