### ISSUE TITLE
Forwarding address for the admins

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#393]
Is there a free service we can use to multiple admin@nix-community.org to all our emails?

Could be useful for #392 as well

**Comment by Mic92** [comment]
I could provide forwarding from my email server.

**Comment by zimbatm** [comment]
Why not. Ideally, we want something where forwarding addresses are configurable with terraform / Nix.

**Comment by Mic92** [comment]
It would be nix, but not inside this repository. I don't think that traditionally mail servers have good integration yet with terraform. However I can configure a regex that allows to match and redirect multiple email addresses so that we only need to reconfigure when the admin list changes.

**Comment by zimbatm** [comment]
If we move the domain to Gandi, we could use their free email forwarding service: https://registry.terraform.io/providers/go-gandi/gandi/latest/docs/resources/email_forwarding

**Comment by zimbatm** [comment]
Once that's done, we'll also have to fix all of our accounts:
* [ ] Terraform Cloud
* [ ] Gandi
* [ ] Github org
* ???

**Comment by zowoq** [comment]
Checked that forwarding works (thanks @ryantm).

Updated
- terraform cloud: https://app.terraform.io/app/nix-community/settings/profile
- github: https://github.com/organizations/nix-community/settings/profile

___

Cloudflare only lets us have one super admin, guess we should move that to admin@nix-community as well?

![cloudflare](https://user-images.githubusercontent.com/59103226/226147721-fd4edcd2-5335-4b85-bf0a-1b6712efb045.png)

**Comment by zimbatm** [comment]
Fixed Cloudflare. The account is requiring a 2FA token so password reset is not enough to gain control. Is there a good place to share the TOTP token?

**Comment by zowoq** [comment]
We could put the topt secret in [infra/secrets.yaml](https://github.com/nix-community/infra/blob/master/secrets.yaml)?

**Comment by zimbatm** [comment]
Ok I think that's it for now
