### ISSUE TITLE
Move the domains to Gandi

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#396]
I want to avoid hidden dependencies. Right now the domains are held by numtide. We need a credit card for this.

**Comment by zimbatm** [comment]
@nlewo also pointed me to Gandi. They have a free offering for open-source projects: https://www.gandi.net/en/gandi-supports

**Comment by nlewo** [comment]
I asked Gandi people in charge of supporting projects and Gandi could offer the nix-commnunity.org domain (mail forwards and more as well i guess).

If you want to move domains to Gandi, I could provide some helps (initial setup, contacts, ...).

**Comment by zimbatm** [comment]
That would be perfect for us. Is the communication with them happening via email?

**Comment by nlewo** [comment]
To ease the process, I will send an introduction mail to legit people.

**Comment by zimbatm** [comment]
Waiting on https://nixpk.gs/pr-tracker.html?pr=214956 to appear in nixos-unstable

**Comment by zowoq** [comment]
This was done in https://github.com/nix-community/infra/pull/418.
