### ISSUE TITLE
Create an Open Collective for the org

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#397]
This could be used to pay for #396 and servers.

Right now servers are paid for by ryantm and Numtide.

**Comment by Mic92** [comment]
build04 is running on my credit card but does not cost anything (free tier).

**Comment by zowoq** [comment]
Open Collective seems like the easiest option, looks like it's already popular in the nix ecosystem.

> build04 is running on my credit card but does not cost anything (free tier).

I tried to make an account to spin up one of these a couple of weeks ago but they rejected my card. Rather surprising as I've not had any issues with it previously, unfortunately seems that it is a reasonably common problem with oracle.

**Comment by zimbatm** [comment]
@adisbladis @ryantm any objections?

**Comment by zimbatm** [comment]
I invited everybody to the open collective and prepared to re-add the banner^

**Comment by zimbatm** [comment]
I also filled out https://oceu.typeform.com/apply so we can use https://opencollective.com/europe as a fiscal host.

**Comment by zimbatm** [comment]
They sent me an email back, I am supposed to meet them Monday/Tuesday for some administrative talk. I will let you know once I have the calendar invite, in case you want to join the call.

**Comment by zimbatm** [comment]
Here is a recap of the call:

* I have to apply the collective to OpenCollective Europe. It should be approved today.
* Minimum of 2 admins must have their full legal names. The Legal Name field is private to the collective.
* The collective has the status of the Belgian ASBL, and USA non-profilt. This means we can ask for fiscal deductibility in Europe and USA for bigger grands (eg: 2k+).
* We can get a Virtual Credit Card after 1k budget. He will send me the info.

As admins, we are responsible to check that the reported expenses have a valid fiscal document attached to them. Typically an order confirmation doesn't count, it needs to be an invoice. Once the expense has been approved, they will double-check that it's valid before issuing the reimbursement.

**Comment by zowoq** [comment]
Guess I shouldn't have forgotten about the call, I had it on my calendar but didn't notice the reminder until a half hour later.

> Minimum of 2 admins must have their full legal names.

Didn't expect this as looks like some collectives have a single admin, but I suppose it depends on where they're hosted, etc.

Didn't think about the legal/financial stuff at all TBH, just signed up when I got the opencollective invite.

Right now I'd prefer to not to do this, I'm fine with not having admin on opencollective if that makes things simpler. Might be better for the org as well if the financial controllers are public people and not pseudonymous?

**Comment by zimbatm** [comment]
I would prefer that we were all represented but it's up to you.

The requirement is already met between me and Jorg, so you have no requirement to list your full name.

Legally, the exposure is pretty small for us. As long as we don't use the collective to do illegal things like money laundering, or sell Nix pills :) The fiscal host is the one that is on the hook, and they will double-check all the expenses that we submit. Even if one member did something fishy, I would expect it to fall on them instead of the whole group.

In terms of pseudonyms; I think that trust is something that is earned. We disagree on some topics sometimes but I trust your base character from all the interactions that we had. "Real" identities are overrated IMO. Virtual identities might be cheaper to create but there is still a lot of effort that goes into creating and establishing a new one.

**Comment by zimbatm** [comment]
I also got this email back from Ivan:

To summarise our discussion:
* when hosted by OCE you will enjoy the non profit status which allows your donors to have tax deductibility both in Europe and in the US,
* the administrators are the sole responsables of the work of the collective,
* for the expenses, [this procedure](https://docs.opencollective.com/oceurope/how-it-works/expenses) applies,
* your initiative/collective cannot have outside bank accounts. All funds must be held in your Open Collective account in order to accurately represent your budget/activities,
* [this](https://docs.opencollective.com/help/) is the place where you can always find help and documentation related to Open Collective.
Pricing wise, the following rates apply:
* 6% fee for online (non tax-deductible) donations,
* 8% fee for wire payments (including grants from Foundations (US or not US-based)),
* 10% fee for tax-deductible donations in the US.

Feel free to put us in touch with the potential funders if any explanations are needed about donating with tax deductibility. 
Finally, if you'd like to receive tax-deductible donations from individuals based in the US, there is the option to create a crowdfunding page with our US partner Foundation.

**Comment by zimbatm** [comment]
I think this can be closed, or should this be captured anywhere?

**Comment by Mic92** [comment]
I think the readme should mention that `nix-community` is a non-profit that accepts donations.

**Comment by ryantm** [comment]
No objections here. I finally signed up and became an admin!

**Comment by zimbatm** [comment]
I think we reached that first goal! Closing.

**Comment by zimbatm** [comment]
I also created https://github.com/nix-community/infra/issues/440 as a follow-up.
