### ISSUE TITLE
admin access to services

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#399]
- [x] buildkite - not currently in use (looks like we could use terraform for this)
- [x] cachix
- [x] cloudflare - https://github.com/nix-community/infra/pull/408
- [x] gandi 
- [x] hercules - looks like org owners get admin automatically
- [x] matrix
  - [ ] #community-monitoring:nixos.dev
  - [ ] #nix-community:nixos.org
- [x] open collective 
- [x] terraform cloud - https://github.com/nix-community/infra/pull/394, https://github.com/nix-community/infra/pull/404

___

I'll leave the server hardware off this list as we have do have access via sops secrets and consolidating those accounts is more a finance issue.

**Comment by zimbatm** [comment]
* buildkite: deleted
* cachix: invited everybody
* gandi: invited everybody
* open collective: invited everybody
* matrix: made everybody admin

**Comment by zimbatm** [comment]
would it make sense to add this to an on-boarding/off-boarding list?

**Comment by zowoq** [comment]
Yes, opened another issue for that. https://github.com/nix-community/infra/issues/423

**Comment by zowoq** [comment]
https://gitlab.com/nix-community

Is this anything to do with us?

**Comment by zimbatm** [comment]
Yes, not sure if it's worth keeping. @adisbladis ?

**Comment by Mic92** [comment]
I think it might be worth to have a backup in case someone maliciously deletes repositories or github decides to ban us for whatever reason (we just received a DMCA takedown order).

I have some terraform code to automatically create mirrors from github to gitlab: https://github.com/Mic92/dotfiles/blob/main/terraform/gitlab/repo-mirror.tf

**Comment by zimbatm** [comment]
k, invited everybody
