### ISSUE TITLE
Get n11y.org as a domain?

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#410]
This would allow for keeping the domains short. Eg: https://hydra.n11y.org
But maybe that's just my dislike of typing :)

**Comment by ryantm** [comment]
Can we change our name to this? Solves two problems.

**Comment by zimbatm** [comment]
I'm up for it, but wouldn't it break many things on GitHub if we renamed the org?

**Comment by ryantm** [comment]
It would break tons of things. I feel like a name change is warranted because the current name is too generic.

**Comment by zimbatm** [comment]
Agreed. It has been bothering me for a long time as well. The name is too long and doesn't represent the project very well. The actual Nix Community is larger than this project.

**Comment by zowoq** [comment]
> I'm up for it, but wouldn't it break many things on GitHub if we renamed the org?

I'd suggest creating a new github org while keeping `nix-community` as a permanent placeholder. Would allow us to move things over gradually and hopefully avoid breaking a bunch of stuff.

Getting CI to work across two orgs may require a bit of work but I don't mind dealing with that.

**Comment by zowoq** [comment]
https://github.com/n11y is in use. 

I guess having `github org == domain` would be nice and simple, do we want to pick something else?

**Comment by zowoq** [comment]
@zimbatm What to you want to do here? Pick something else or use a variation of `n11y`, e.g. `github.com/n11y-org`?

**Comment by adisbladis** [comment]
I'm not a fan of using numeronyms in org/domain names. I think it would be a significant downgrade in clarity.

**Comment by Mic92** [comment]
I also like the current name better. It's easier to spell.
