### ISSUE TITLE
Gitlab as a backup

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#424]
I think it might be worth to have a backup in case someone maliciously deletes repositories or github decides to ban us for whatever reason (we just received a DMCA takedown order).

I have some terraform code to automatically create mirrors from github to gitlab: https://github.com/Mic92/dotfiles/blob/main/terraform/gitlab/repo-mirror.tf

_Originally posted by @Mic92 in https://github.com/nix-community/infra/issues/399#issuecomment-1407029221_

**Comment by Mic92** [comment]
I have not received any invite to the nix-community gitlab org. Here is my handle: https://gitlab.com/Mic92

**Comment by zowoq** [comment]
Don't think there was an invite but we've all been made members of the org.

**Comment by zimbatm** [comment]
You should have access:
![image](https://user-images.githubusercontent.com/3248/215285430-26ba6829-a7a9-4aa5-a61c-2002508558b1.png)
source: https://gitlab.com/groups/nix-community/-/group_members

**Comment by ryantm** [comment]
Thanks. I set up 2factor auth on Gitlab.

**Comment by Mic92** [comment]
Mirror is here https://github.com/nix-community/infra/pull/521

**Comment by zowoq** [comment]
We're using borg to do a daily backup the repos to the storage box. https://github.com/nix-community/infra/pull/564

Can revisit this later if we want a public mirror.
