### ISSUE TITLE
I would like to maintain the templates repo

### ISSUE THREAD

**Issue by IogaMaster** [nix-community/infra#443]
https://github.com/nix-community/templates

How would I go about becoming a maintainer?

I would like to keep the license the same.

**Comment by zimbatm** [comment]
Typically we move repos to the org only after they matured a bit. I'm not exactly sure what happened with this one. @garbas do you still have plans for this repo?

@IogaMaster a good start is to fork the repo and build it up in your own account. Mature it a bit. Once you did that, I don't see any other obvious blockers.

**Comment by garbas** [comment]
Sorry for late reply.

Idea was to move templates from nixos/templates here and start from scratch there. Having a very opinionated templates there and more community driven templates here. Those opinionated templates were suppose to target newcomers to Nix while more experienced users would most likely find community templates more useful. The basic strategy to not confuse newcomers with too many options. You can see that having more templates how to start python project will confuse newcomers, but more experienced users might want to use a python template with poetry2nix example there.

Personally I don't have time to push this further, but I hope somebody will drive such efforts further.

**Comment by Mic92** [comment]
I sent you an invite @IogaMaster

**Comment by IogaMaster** [comment]
I feel it would be better if I mature the repo for a few months, get it in a state I feel happy with before I join.

**Comment by IogaMaster** [comment]
@Mic92 I am ready to join nix-community

**Comment by Mic92** [comment]
@IogaMaster invite sent.

**Comment by IogaMaster** [comment]
Thanks!

**Comment by IogaMaster** [comment]
Could you give me edit access to the templates repository?

**Comment by IogaMaster** [comment]
@Mic92 Could you give me write access to the repository? Thanks!

**Comment by adisbladis** [comment]
> @Mic92 Could you give me write access to the repository? Thanks!

I've added you to the templates team, so you now have access.

**Comment by IogaMaster** [comment]
Thanks!
