### ISSUE TITLE
emacs package builds broken on build01

### ISSUE THREAD

**Issue by talyz** [nix-community/infra#47]
5 days ago emacs package updates stopped in the [nix-community/emacs-overlay](https://github.com/nix-community/emacs-overlay) repo probably due to f47b49e5018277f73c6c93ee0ab85519ade4ac16. See the log at https://gitlab.com/nix-community/emacs-overlay/-/jobs/967612808, from line 485 and on.

Related issue: https://github.com/nix-community/emacs-overlay/issues/104

cc @ryantm

**Comment by ryantm** [comment]
@talyz Sorry about that and thanks for letting me know. I reverted the change!

https://github.com/nix-community/infra/commit/ae11986b8ec4910636fbabea96f4101da966ad0f

**Comment by talyz** [comment]
Thanks! The builds work again :tada:
