### ISSUE TITLE
nixpkgs-update logs backup

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#541]
https://r.ryantm.com/log/

I was going to do a manual backup of these logs before reinstalling build02 but I suppose we should really be doing regular backups so they aren't all lost if build02 dies.

If we don't have somewhere external to nix-community to back them up to I guess we'd want backups on a couple of our machines?

cc @nix-community/admin

**Comment by Mic92** [comment]
We might have backup storage provided by hetzner that comes with the hardware. Their storage boxes support borgbackup.

**Comment by zowoq** [comment]
> We might have backup storage provided by hetzner that comes with the hardware.

If we do have this it doesn't seem to be accessible with the credentials in the top level secrets so would need someone else with access to deal with it on the hetnzer side.

> Their storage boxes support borgbackup.

This looks like it'll do what we want and it's simple to set up, hopefully we can use it.

**Comment by Mic92** [comment]
I'll have a look at it.

**Comment by zowoq** [comment]
I'll set this up in the next couple of days.
