### ISSUE TITLE
S.M.A.R.T errors on build01

### ISSUE THREAD

**Issue by Mic92** [nix-community/infra#55]
Result of `smartctl --all /dev/sd{a,b}`:

[sdb.log](https://github.com/nix-community/infra/files/6042784/sdb.log)
[sda.log](https://github.com/nix-community/infra/files/6042785/sda.log)

Summary:

```
=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: FAILED!
Drive failure expected in less than 24 hours. SAVE ALL DATA.
No failed Attributes found.
# ...
202 Percent_Lifetime_Used   0x0030   001   001   001    Old_age   Offline  FAILING_NOW 99
```

Apparently disks are EOL, no data error visible.
Should we ask Hetzner for new drives or ignore the error?

**Comment by adisbladis** [comment]
cc @zimbatm

**Comment by zimbatm** [comment]
We need a replacement machine. Hetzner will take the machine out of commission

**Comment by Mic92** [comment]
I can deal with the installation if you want.

**Comment by Mic92** [comment]
Waiting now for the new server to be provisioned by hetzner.

**Comment by Mic92** [comment]
I have no access to the server.

**Comment by zimbatm** [comment]
Are we still having those SMART errors?

**Comment by Mic92** [comment]
Yes.

**Comment by Mic92** [comment]
Fixed.
