### ISSUE TITLE
monitoring

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#558]
I'd like to host our own monitoring so we are self sufficient.

I guess we could switch to something else but easiest option is import the monitoring we're currently using from https://github.com/Mic92/dotfiles.

I'd focus on getting it working here first but eventually we could look at sharing the boilerplate config, maybe https://github.com/numtide/srvos or somewhere else.

Would also like set up a dashboard as well.

**Comment by zimbatm** [comment]
The Gandi VM might be a good fit if we're not already using it for something else. It makes sure that the monitoring doesn't get impacted at the same time in case the issue is with the region / cloud-provider.

**Comment by zowoq** [comment]
> The Gandi VM might be a good fit if we're not already using it for something else.

@Mic92 was going to use it for the wiki. Not sure if we could run monitoring on there as well?

https://www.gandi.net/en/cloud/vps

The gandi email said "up to 4 vcpus" and "up to the V-R4 flavor". Looks like "V-R4" is 2 cpu?

**Comment by Mic92** [comment]
> > The Gandi VM might be a good fit if we're not already using it for something else.
> 
> @Mic92 was going to use it for the wiki. Not sure if we could run monitoring on there as well?

Would be great to keep using it for that. I have now slowly prepared nixpkgs so I can use the mediawiki from there.

**Comment by nlewo** [comment]
> The gandi email said "up to 4 vcpus" and "up to the V-R4 flavor". Looks like "V-R4" is 2 cpu?

You asked for a V-R4 (with 2 cpus) but the quota allow you to create up to 4 vcpus. So, you could create a V-R1 for the monitoring ;)

**Comment by zowoq** [comment]
Done in https://github.com/nix-community/infra/pull/711, https://github.com/nix-community/infra/pull/691.

Will continue work on a dashboard in https://github.com/nix-community/infra/pull/753.
