### ISSUE TITLE
password management

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#569]
Not really a problem at the moment but if we keep adding accounts to the top level `secrets.yaml` we may want something easier to use?

1password has an open source program: https://github.com/1Password/1password-teams-open-source

Could try bitwarden as well but I think we'd need to host it ourselves or pay for it?

**Comment by zowoq** [comment]
> Bitwarden also has an open-source program that we can ask for. I did the setup for the NixOS Foundation.

Is this a discounted or free?

**Comment by zimbatm** [comment]
Should be free

**Comment by Mic92** [comment]
After following how security was handled in 1password, I would no longer consider switching to it.

**Comment by zimbatm** [comment]
I'm interested, do you have a source?

**Comment by Mic92** [comment]
Ah. Sorry. I mixed it up with lastpass. 1password might be fine, never tested it. Bitwarden works well for me. I am using the hosted and self-hosted version every day.

**Comment by zowoq** [comment]
The hosted Bitwarden teams option is $3 user/month x 5 admins = $180/year.

The NixOS foundation was offered a 25% non-profit discount so we might be able to get it for $135/year.

We probably don't want to spend that much and I don't think we want to self host it either.

It's only "free as in beer" but I think the 1password open source program is the best option available to us at the moment.

**Comment by zimbatm** [comment]
What if I arranged for us to have a category on the NixOS Bitwarden? On the plus side: it would be free for the nix-community org. On the down side: you wouldn´t have admin on the Org

**Comment by zowoq** [comment]
> What if I arranged for us to have a category on the NixOS Bitwarden? On the plus side: it would be free for the nix-community org. On the down side: you wouldn´t have admin on the Org.

I can go into more detail if you like but TLDR: I don't think us binding ourselves closer to the foundation is a good idea.

**Comment by zowoq** [comment]
https://github.com/nix-community/infra/pull/876

Using `sotp` now so we can put off making a decision about this, closing.
