### ISSUE TITLE
renovate bot

### ISSUE THREAD

**Issue by Mic92** [nix-community/infra#572]
I think it would be cool to have a bot that can update nix dependencies nativly: https://github.com/renovatebot/renovate

There is a github actions https://github.com/DeterminateSystems/update-flake-lock however because of api limitations it cannot trigger github actions, making auto-merging difficult. Historically I used to use bors for that but this one is also about to be removed.

**Comment by zowoq** [comment]
Is this for use in this repo or do you mean to enable it org wide like the settings app? https://github.com/orgs/nix-community/discussions/402

**Comment by Mic92** [comment]
I'd say it could be enabled org wide. The repo here does not have the problem as much because it does not uses the github actions runner. However many other projects do.

**Comment by zowoq** [comment]
> I'd say it could be enabled org wide.

> https://github.com/marketplace/renovate
> Install the app and select the repos you would like. For each selected repo, an Onboarding PR will be created.

**Comment by Mic92** [comment]
Do repo admins have enough power to enable apps for their repo?

**Comment by Mic92** [comment]
I have tried the bot for nix but it seemed to have issues with api tokens when updating github-based flakes. That was the hosted version. I may try the self-hosted one some time to see, if I can see the issue there as well.
