### ISSUE TITLE
Apply for scaleways open source program

### ISSUE THREAD

**Issue by phaer** [nix-community/infra#574]
Hello,

Following up the discussion in #493, we've learned about [Scaleways Open Source Program](https://www.scaleway.com/en/about-us/open-source-program/) and started talking about applying as Nix-Community and ask for one or more M1 machines to use in our CI builder.

Do you think its a good idea to apply there? This has so far been discussed with @DavHau and @RaitoBezarius and I've been asked to ping @Mic92 and @zimbatm here :)

If we'd draft an application here, could we do this in the name of the existing legal entity for nix-community?

This is a parallel effort and maybe a viable alternative to a physical machine, which could be more powerful but would probably require more maintenance from our side - see recent comments in #493 for more info on that approach.

**Comment by zimbatm** [comment]
Sounds good!

> If we'd draft an application here, could we do this in the name of the existing legal entity for nix-community?

We don't have a legal entity. We're using OSC Europe as our fiscal host only. Can we apply as individual users or as a non-legal entity?

**Comment by Mic92** [comment]
I wonder at which point it would make sense to create a non-profit organization though. The nixos foundation is a bit too congested for doing things, I feel.

**Comment by phaer** [comment]
> We don't have a legal entity. We're using OSC Europe as our fiscal host only. Can we apply as individual users or as a non-legal entity?

Ah good to know, I understood @RaitoBezarius thought there was already one and if so that would have been useful. Scaleway says

> If you are a non-profit entity (foundation, association, etc.), or a community project (open community governance)

Where I don't know the specifics about the latter part, but I think it implies that it would work without a formal legal entity. Let's find out by applying :)

**Comment by RaitoBezarius** [comment]
> Ah good to know, I understood @RaitoBezarius thought there was already one and if so that would have been useful. Scaleway says

This is because @Mic92 told so : https://discourse.nixos.org/t/vulnix-new-maintainer-needed/27209/12 :D

**Comment by zimbatm** [comment]
nice, if you can you add admin <at> nix-community <dot> org in CC that would perfect

**Comment by Mic92** [comment]
I think the application got declined because they don't accept more project at the moment?

**Comment by phaer** [comment]
Yes, their open source program is "taking a break" until 2024 - we can re-apply in Dec 2023

**Comment by Mic92** [comment]
closing just now.
