### ISSUE TITLE
`#community-monitoring`

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#579]
This room has been getting worse for the last couple of weeks, loads slowly or doesn't load at all.

Also have to login to see the room which wasn't necessary until recently.

Haven't noticed any problems with other rooms.

**Comment by Mic92** [comment]
I don't see this problem on my end. From my understanding, matrix rooms are not hosted on a single server. However let's see if changing the main address from nixos.dev to something else makes it better.

**Comment by zowoq** [comment]
I can see the room without signing in now and it loads quickly.

Strange that changing the address fixes it.

**Comment by zowoq** [comment]
Is this room something we should host ourselves?

Like with the monitoring I'd to avoid depending on personal infra but we'd want this room to still work even if the server it's hosted on is offline.

**Comment by Mic92** [comment]
It's possible to also just add multiple addresses for a channel than it's depending on multiple servers being down.

**Comment by zowoq** [comment]
Do we have full control of the room even if we're not hosting it ourselves?

Don't really want to host it ourselves but also don't want to depend on other servers that may eventually disappear one day.

I guess moving to `nixos.org` is a safe option but not sure if that is a direction we want to move in.

Almost wondering if we should just use something like zulip cloud? I haven't used it myself but AFAIK we can set webhooks for alertmanager and github and we wouldn't need to host the room/server or go-neb.

**Comment by zowoq** [comment]
@Mic92 Can we move this room to `matrix.org`?

**Comment by zimbatm** [comment]
Go for it. The room can be easily moved and your account is attached to matrix.org

**Comment by zowoq** [comment]
Moved and updated the docs: https://github.com/nix-community/infra/pull/693.
