### ISSUE TITLE
Naming scheme for boxes

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#591]
Something that came up in #589.

As the infrastructure is growing, I think the current naming scheme doesn't scale very well. It might be worth finding another scheme.

What do you think of (1) renaming the machines so they arch and kernel? Eg:

* x86-64-linux-01
* aarch64-darwin-01

Or (2) use the role of the machine as the name. Eg:

* nixpkgs-update-01
* hercules-agent-linux-aarch64-01
* remote-builder-darwin-aarch64-01
* community-box-01

Or (3) use some pet names for each of the machines.

I don't want to spend too much time discussing this but maybe something jumps out that we can quickly agree on.

**Comment by zowoq** [comment]
Pet names.

The others are too specific and kind of confusing or misleading.

**Comment by zowoq** [comment]
Perhaps petnames aren't a good idea, kind of awkward to automate.

Could just rename build to nixos and leave it at that. 

```
  darwin01
  nixos01
  nixos02
  nixos03
  nixos03
```

**Comment by zowoq** [comment]
Looking at all the things we'd need to do (secrets, dns, lots more) for renaming the existing machines I'm not sure that it is worth the effort.

We all know that `build` == `nixos`, if we ever add any non-nixos machines besides darwin we just call them something that isn't `build`.

**Comment by Mic92** [comment]
Either build or nixos sounds fine to me.

**Comment by zowoq** [comment]
With https://github.com/nix-community/infra/issues/645#issuecomment-1611511336 we're using build, darwin and web so I think this is resolved for now.
