### ISSUE TITLE
organisation members team

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#604]
Currently we don't have a way to `@` everyone in the org.

Adding the current org members to a team is insufficient as we have ~30 outside collaborators we'd still need to `@` manually.

I'd propose that only bot accounts are allowed to be collaborators and that people are required to be org members so we can contact them all as a group.

**Comment by zimbatm** [comment]
What kind of messages do you want to send to them? I'm asking because mass pings are generally frowned upon.

**Comment by zowoq** [comment]
> I'm asking because mass pings are generally frowned upon.

Yes, this is something that will only be used rarely. I considered writing a script to generate a list of members and collaborators but github limits the number of users that can be pinged in each message which makes that approach awkward.

> What kind of messages do you want to send to them?

What made we think of it was this:

>> https://github.com/nix-community/infra/issues/534#issuecomment-1514786986
>>  Ideally, the org holds projects that are more than MVPs, although we didn't really discuss what standards we want to hold here. 

I was going to create a discussion about what standards we want to apply, would ping everyone for that.

Hypothetical examples: moderation policies, significant infrastructure changes.

**Comment by zowoq** [comment]
I always forgot that it exists. I'll try to remember to use it and link to it from matrix, etc.

I'll close this issue as trying to manage a github team of all members / collaborators will probably be more hassle than it is worth. Announcing on discussions and the matrix channel is likely sufficient. Could also post to https://discourse.nixos.org/ if necessary.
