### ISSUE TITLE
Running first-time-contribution-tagger on community hardware

### ISSUE THREAD

**Issue by Janik-Haag** [nix-community/infra#634]
I recently wrote a [small-ish application](https://github.com/janik-Haag/first-time-contribution-tagger) tagging PRs of first time contributors with a specified lable. I also wrote a [discourse post](https://discourse.nixos.org/t/showing-first-time-contributors-some-love/29105) about it where someone asked "shouldn't this be running on official infra" and that's why I'm opening the issue.

**Comment by zowoq** [comment]
Based on the comments and the link posted in the discourse thread I think you've open this in the wrong place, this repo is nix-community infra, we aren't official.

The repo for official infra is https://github.com/NixOS/nixos-org-configurations.

**Comment by Janik-Haag** [comment]
I guess, but as far as I undestood nixos-org-configuration is like critical infra and this is the less critical infra which seems like it's the more appropriate place.

**Comment by zowoq** [comment]
> I guess, but as far as I undestood nixos-org-configuration is like critical infra and this is the less critical infra which seems like it's the more appropriate place.

nixos-org-configuration isn't "critical" and this repo isn't "less critical", the difference between them is official and non-official.

> "shouldn't this be running on official infra"

We can probably run it here but I want to be clear that this is not "official infra".

**Comment by mightyiam** [comment]
I'd say this should be official.

**Comment by Mic92** [comment]
Being able to run services like this with a bigger bus factor is why we create the nix-community infra. So I am all for it.

**Comment by Janik-Haag** [comment]
I would also feel more comfortable with the community infra.

**Comment by zowoq** [comment]
> Being able to run services like this with a bigger bus factor is why we create the nix-community infra.

https://github.com/NixOS/nixos-org-configurations/commit/db6bf66337e6da19bab0007f3a756cf2c62d98a1

Yeah until recently I would have been fine with us just running it here but one of the motivations for splitting and expanding the nixos infra team was so they can better handle this sort of thing, I'd prefer that they have a chance to discuss running it first before we do anything.

**Comment by zowoq** [comment]
TBH I think with the recent nixos infra team changes it's probably easiest for us to set a policy that apps/bots/websites that are nixpkgs specific (e.g. this or something like https://nixpk.gs/pr-tracker.html) are out of scope for us unless there are reasons for it not to be run on nixos org infra (e.g. nixpkgs-update bot needs dedicated hardware and cache).

**Comment by Janik-Haag** [comment]
So I should just open the same issue for nixos infra?

**Comment by mightyiam** [comment]
> So I should just open the same issue for nixos infra?

Seems like it

**Comment by zowoq** [comment]
> So I should just open the same issue for nixos infra?

Yes, please do so. If it turns out that there isn't any interest in hosting it on the official infra we can reconsider hosting it here.

**Comment by Janik-Haag** [comment]
Opend the issue in the other repo. Closing here for now
