### ISSUE TITLE
Deploy Lemmy

### ISSUE THREAD

**Issue by zimbatm** [nix-community/infra#645]
@adisbladis interested in deploying a Lemmy instance.

We'll get a small Hetzner VM and deploy it directly there.

Any objections?

**Comment by zowoq** [comment]
> ... interested in deploying a Lemmy instance.

Are `nix-community` admins going to be expected to moderate it?

> We'll get a small Hetzner VM and deploy it directly there.

Would this be fairly similar to what we have already, e.g. in the same flake as the others as `build05` and `inputs.self.nixosModules.lemmy`?

**Comment by Mic92** [comment]
What would this name schema be? "build05"?

**Comment by zowoq** [comment]
Yes. We'd discussed naming in https://github.com/nix-community/infra/issues/591 as well.

**Comment by zimbatm** [comment]
> What does requests mean? Do the mods approve posts before they are made visible?

I mean requests for moderation. If somebody is unhappy and wants to request our intervention.

**Comment by adisbladis** [comment]
> Are `nix-community` admins going to be expected to moderate it?

That's a very good question. I imagined that moderation would be handled by a completely separate set of moderators day-to-day, but that nix-community admins would get admin access.

As for the instance name I'm leaning towards `web01`. It's in line with our schema and gives us room to deploy more web services to the same instance.

**Comment by zimbatm** [comment]
Alright, it looks like we converged.

**Comment by zowoq** [comment]
Couple of thoughts:

- Backups: guess we can use the hetzner storage box for this?

- GDPR stuff: I know very little about this sort of thing, are there any rules that we need to make sure we're following?

**Comment by adisbladis** [comment]
> Backups: guess we can use the hetzner storage box for this?

I was planning to use [pgBackRest](https://bun.uptrace.dev/postgres/pgbackrest-s3-backups.html). This could be used with Hetzner Storage Box by mounting it locally and pointing a Minio instance to it.
