### ISSUE TITLE
Branch protection and merge queue don't work with PRs from forks

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#701]
I had to disable branch protection for https://github.com/nix-community/infra/pull/700, it wasn't tested by CI before merging.

Probably just need to tweak the rules to fix it but as we don't get many PRs from forks fixing it isn't a high priority for me.

Added a workaround for this with an action in https://github.com/nix-community/infra/pull/793.

**Comment by Mic92** [comment]
Yes merge queues from github don't work for opensource at all. That's why I am deploying mergify everywhere.

**Comment by zowoq** [comment]
This is only a problem because we are using hercules, it won't be an issue once we switch to buildbot.

**Comment by Mic92** [comment]
As far as I know you cannot put pull requests from forks into merge queues at all.

**Comment by zowoq** [comment]
> put pull requests from forks into merge queues

We are currently doing this, it just required a hack to get it to work with hercules.

**Comment by zowoq** [comment]
This all works correctly now we've using buildbot.
