### ISSUE TITLE
nixpkgs-update workers are occasionally eating garbage

### ISSUE THREAD

**Issue by rhendric** [nix-community/infra#799]
The FIFO used to communicate between fetchers and workers is not a safe replacement for a proper task queue.

Excerpts from https://r.ryantm.com/log/~workers/2023-08-31-worker1.stderr.log:
```
+ /var/lib/nixpkgs-update/bin/nixpkgs-update update-batch --pr --outpaths --nixpkgs-review 'rg.r/rjc/tlasle/esoshaskellPackages.llvm-dsl 0.0 0.1 https://repology.org/project/haskell:llvm-dsl/versions'
[...]
+ /var/lib/nixpkgs-update/bin/nixpkgs-update update-batch --pr --outpaths --nixpkgs-review 'ython31akgsti-esce .0201. tp:/eooyogpoetpto:rowboktvrin'
```
And from https://r.ryantm.com/log/~workers/2023-08-31-worker2.stderr.log:
```
+ /var/lib/nixpkgs-update/bin/nixpkgs-update update-batch --pr --outpaths --nixpkgs-review 'p1Pcae.rowbokt01. .03hts/rplg.r/rjc/yhnti-esce/esoskabeljau 1.2.0 2.0.0 https://repology.org/project/kabeljau/versions'
```

I want to replace the FIFO with a queue service using sockets, and make the queue a least-recently-updated priority queue while I'm at it; this issue is just advance warning of my intentions, in case they interfere with someone else's.

**Comment by zowoq** [comment]
cc @ryantm

**Comment by zowoq** [comment]
Bit of a tangent but it would be useful if we had some way of verifying the bot is actually working, e.g. check if the bot has opened a PR in nixpkgs the last few hours and fire an alert if it hasn't. Twice now the bot has been broken and I only noticed because it hadn't opened any PRs for a day or two.
