### ISSUE TITLE
Automatically publish logs from r-ryantm runs

### ISSUE THREAD

**Issue by Synthetica9** [nix-community/infra#9]
Similar to how @ryantm used to do at https://discourse.nixos.org/t/nixpkgs-update-r-ryantm-logs/1464

**Comment by ryantm** [comment]
I am still planning to do this manually until I automate this.

**Comment by ryantm** [comment]
They are now automatically available at https://r.ryantm.com/log/

**Comment by Mic92** [comment]
Really cool. I wonder if it was possible to publish them in a more structured way. For example json lines. Than people could write tools to analyze the logs better.

**Comment by Mic92** [comment]
It would be also helpful to set the `Content-Type: text/html; charset=utf-8` header so that browser do not interpret them as latin-1.

**Comment by ryantm** [comment]
@Mic92 I set the charset to utf-8. I didn't adjust the content type though, because the logs are plain text.
