### ISSUE TITLE
nixpkgs-update worker1 is AWOL

### ISSUE THREAD

**Issue by rhendric** [nix-community/infra#945]
There are no log files for worker1 in https://r.ryantm.com/log/~workers/ since Monday.

Curious fact: the last package worker1 was processing was `python310Packages.mmengine`. The previous time `python310Packages.mmengine` was processed was [October 14](https://r.ryantm.com/log/python310Packages.mmengine/), and examining https://r.ryantm.com/log/~workers/ shows that worker2 went AWOL for a briefer time on October 14 (the last modified time for its log file is substantially before midnight), [immediately after processing the same package](https://r.ryantm.com/log/~workers/2023-10-14-worker2.stderr.log). Out of a queue of 20,000+ packages (currently), that's a pretty suspicious coincidence, but I don't know what to make of it yet.

I'd be curious to know what the status of the worker1 service on build02 is right now, and if there are any journal messages that shed light on why it's stuck.

**Comment by zowoq** [comment]
Not sure what happened, it was just sitting at `eval end`, not using any resources.

**Comment by zowoq** [comment]
Forget to say that a week ago I killed another `python310Packages.mmengine` update that had been stuck for six hours or so.

**Comment by zowoq** [comment]
The linked PRs have been deployed for a couple of weeks now, closing.
