### ISSUE TITLE
transfer `nixpkgs-update` to `nix-community`

### ISSUE THREAD

**Issue by zowoq** [nix-community/infra#984]
- [x] ~~transfer `build02` to `nix-community` hetzner account~~ created a new machine on the nix-community account 
- [x] transfer https://github.com/ryantm/nixpkgs-update repo to `nix-community` organisation
- [x] transfer https://github.com/Synthetica9/nixpkgs-update-github-releases repo to `nix-community` organisation
- [x] transfer `r-ryantm` github account to `nix-community` admins - https://github.com/nix-community/infra/pull/1215

Not sure about the logs, maybe put them on a community domain e.g. `nixpkgs-update.nix-community.org/logs` or `r-ryantm.nix-community.org/logs`? https://github.com/nix-community/infra/pull/1243

Also not sure what to do with https://hackage.haskell.org/package/nixpkgs-update, ~~maybe just delete it~~? ~~Can't be deleted but it can be deprecated. https://hackage.haskell.org/packages/deprecated~~ The nixpkgs haskell tooling doesn't seem to recognize deprecated so there isn't really anything that can we can do with the package on hackage.

**Comment by Synthetica9** [comment]
https://github.com/nix-community/nixpkgs-update-github-releases/issues/9 is done.
